### ISSUE TITLE
Dashboard app not run

### ISSUE THREAD

**Issue by fluttertutorialin** [TheChance101/beep-beep#542]
Please share the steps on how to run the desktop app.

**Comment by fluttertutorialin** [comment]
Exception in thread "main" java.lang.NoClassDefFoundError: cafe/adriel/voyager/core/model/StateScreenModel
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at di.ScreenModelModuleKt$ScreenModelModule$1.invoke(ScreenModelModule.kt:50)
	at di.ScreenModelModuleKt$ScreenModelModule$1.invoke(ScreenModelModule.kt:14)
	at org.koin.dsl.ModuleDSLKt.module(ModuleDSL.kt:44)
	at org.koin.dsl.ModuleDSLKt.module$default(ModuleDSL.kt:42)
	at di.ScreenModelModuleKt.<clinit>(ScreenModelModule.kt:14)
	at di.AppModuleKt$appModule$1.invoke(AppModule.kt:9)
	at di.AppModuleKt$appModule$1.invoke(AppModule.kt:5)
	at org.koin.dsl.ModuleDSLKt.module(ModuleDSL.kt:44)
	at org.koin.dsl.ModuleDSLKt.module$default(ModuleDSL.kt:42)
	at di.AppModuleKt.appModule(AppModule.kt:5)
	at MainKt$main$1.invoke(Main.kt:12)
	at MainKt$main$1.invoke(Main.kt:12)
	at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:65)
	at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:40)
	at MainKt.main(Main.kt:12)
	at MainKt.main(Main.kt)
Caused by: java.lang.ClassNotFoundException: cafe.adriel.voyager.core.model.StateScreenModel
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 34 more

**Comment by ahmednasserzaza** [comment]
Please ensure that you have the correct path for either the 'dashboard app' or the 'support app.' Also, don't forget to specify the Main Class (MainKt), which Android Studio will detect by default after selecting the appropriate classpath module. Please let me know if you have any problem.

![desktop](https://github.com/TheChance101/beep-beep/assets/30028905/4345ab59-4417-4393-97ad-0cd211b491d5)

**Comment by fluttertutorialin** [comment]
Same problem 

<img width="673" alt="Screenshot 2023-11-04 at 6 09 30 PM" src="https://github.com/TheChance101/beep-beep/assets/6063623/6f5feee9-90d3-4224-8f59-aa80bb2ad37b">

**Comment by ahmednasserzaza** [comment]
try this solution to run desktop apps
1 - Add new configuration 
2 - select Gradle
3 - add needed configuration as folows
it's neccessary to add this line at run ( jvmRun -DmainClass=MainKt --quiet )

![1](https://github.com/TheChance101/beep-beep/assets/30028905/3eae103d-c3b0-4681-999c-fc809f8879ca)
![2](https://github.com/TheChance101/beep-beep/assets/30028905/a633f482-c54e-4e12-9c7b-bff7016bf817)

**Comment by fluttertutorialin** [comment]
Solve the problem.
